#1: Added example dashboard
exasol/cloudwatch-dashboard-examples pull request #2
Opened 2021-01-29 08:09 UTC by jakobbraun

Closes #1

2021-02-11 07:58 UTC, morazow requested changes

2021-02-11 07:58 UTC, morazow commented on LICENSE
> +Copyright (c) 2020 Exasol
```suggestion
Copyright (c) 2021 Exasol
```

2021-02-11 07:58 UTC, morazow commented on LICENSE
> +Copyright (c) 2020 Exasol
This should also be changed in the keeper.

2021-02-11 07:58 UTC, morazow commented on README.md
> +This dashboard should fasten your start with Exasol and CloudWatch.
```suggestion
This dashboard should get you started with Exasol and CloudWatch integration.
```

2021-02-11 07:58 UTC, morazow commented on README.md
> +* Adopt the Dashboard to your needs (modify `src/main/java/com/exasol/cloudwatchexampledashboard/CloudwatchDashboardExamplesStack.java`)
```suggestion
* Adapt the dashboard to your needs (modify `src/main/java/com/exasol/cloudwatchexampledashboard/CloudwatchDashboardExamplesStack.java`)
```

2021-02-11 07:58 UTC, morazow commented on README.md
> +* Adopt the Dashboard to your needs (modify `src/main/java/com/exasol/cloudwatchexampledashboard/CloudwatchDashboardExamplesStack.java`)
Would this be possible without modifying the java code? For example, using the a config file (yaml, props, etc).

2021-02-15 06:59 UTC, jakobbraun commented on LICENSE
> +Copyright (c) 2020 Exasol
yes. I created an issue for it: https://github.com/exasol/project-keeper-maven-plugin/issues/69

2021-02-15 07:42 UTC, morazow approved these changes

2021-02-15 07:43 UTC, merged